#!/bin/bash
python makeroot.py --var 'nparticle_eta2p4pt05_pur'
python makeroot.py --var 'nparticle_eta2p4pt05_pur' --inputfilesim '/work/jinw/CMSSW_11_1_0/src/EXOVVNtuplizerRunII/Ntuplizer/flatTuple_MB_TuneUp_trk_noPU_new.root' --MCtag 'tuneup'
python makeroot.py --var 'nparticle_eta2p4pt05_pur' --inputfilesim '/work/jinw/CMSSW_11_1_0/src/EXOVVNtuplizerRunII/Ntuplizer/flatTuple_MB_TuneDown_trk_noPU_new.root' --MCtag 'tunedown'
python makeroot.py --var 'spherocity_eta2p4pt05_pur' 
python makeroot.py --var 'spherocity_eta2p4pt05_pur' --inputfilesim '/work/jinw/CMSSW_11_1_0/src/EXOVVNtuplizerRunII/Ntuplizer/flatTuple_MB_TuneUp_trk_noPU_new.root' --MCtag 'tuneup'
python makeroot.py --var 'spherocity_eta2p4pt05_pur' --inputfilesim '/work/jinw/CMSSW_11_1_0/src/EXOVVNtuplizerRunII/Ntuplizer/flatTuple_MB_TuneDown_trk_noPU_new.root' --MCtag 'tunedown'
python makeroot.py --var 'thrust_eta2p4pt05_pur' 
python makeroot.py --var 'thrust_eta2p4pt05_pur' --inputfilesim '/work/jinw/CMSSW_11_1_0/src/EXOVVNtuplizerRunII/Ntuplizer/flatTuple_MB_TuneUp_trk_noPU_new.root' --MCtag 'tuneup'
python makeroot.py --var 'thrust_eta2p4pt05_pur' --inputfilesim '/work/jinw/CMSSW_11_1_0/src/EXOVVNtuplizerRunII/Ntuplizer/flatTuple_MB_TuneDown_trk_noPU_new.root' --MCtag 'tunedown'
python makeroot.py --var 'broaden_eta2p4pt05_pur'    
python makeroot.py --var 'broaden_eta2p4pt05_pur' --inputfilesim '/work/jinw/CMSSW_11_1_0/src/EXOVVNtuplizerRunII/Ntuplizer/flatTuple_MB_TuneUp_trk_noPU_new.root' --MCtag 'tuneup'
python makeroot.py --var 'broaden_eta2p4pt05_pur' --inputfilesim '/work/jinw/CMSSW_11_1_0/src/EXOVVNtuplizerRunII/Ntuplizer/flatTuple_MB_TuneDown_trk_noPU_new.root' --MCtag 'tunedown'
python makeroot.py --var 'transversespherocity_eta2p4pt05_pur'
python makeroot.py --var 'transversespherocity_eta2p4pt05_pur' --inputfilesim '/work/jinw/CMSSW_11_1_0/src/EXOVVNtuplizerRunII/Ntuplizer/flatTuple_MB_TuneUp_trk_noPU_new.root' --MCtag 'tuneup'
python makeroot.py --var 'transversespherocity_eta2p4pt05_pur' --inputfilesim '/work/jinw/CMSSW_11_1_0/src/EXOVVNtuplizerRunII/Ntuplizer/flatTuple_MB_TuneDown_trk_noPU_new.root' --MCtag 'tunedown'
